import hashlib
import hmac
import os

# 1x1 transparent GIF (smallest valid tracking pixel)
PIXEL_GIF = bytes.fromhex(
    "47494638396101000100800000000000ffffff21f90401000000002c00000000"
    "010001000002024401003b"
)


def get_base_url() -> str:
    return os.getenv("TRACKING_BASE_URL", "http://localhost:8080").rstrip("/")


def _sign(lead_id: int, sequence_id: int) -> str:
    """HMAC-SHA256 signature over (lead_id, sequence_id, secret).

    Without this, an attacker can inflate a lead's open count by hitting
    the pixel URL directly.  See code review S1.
    """
    secret = os.getenv("TRACKING_SECRET", "change-me").encode("utf-8")
    msg = f"{lead_id}:{sequence_id}".encode("utf-8")
    return hmac.new(secret, msg, hashlib.sha256).hexdigest()[:16]


def tracking_url(lead_id: int, sequence_id: int) -> str:
    """Build the tracking-pixel URL for a given lead + sequence step.

    The signature is appended as a query string so the server can verify
    that the request was generated by this pipeline and not replayed by
    an attacker.
    """
    return f"{get_base_url()}/track/{lead_id}/{sequence_id}.png?t={_sign(lead_id, sequence_id)}"


def tracking_pixel_html(lead_id: int, sequence_id: int) -> str:
    """Return an <img> tag pointing at the tracking pixel, for email bodies.

    The signature is part of the URL. The lead/sequence ids are integers
    and the signature is hex, so the URL cannot break out of the
    `src="..."` attribute even if TRACKING_BASE_URL is misconfigured.
    """
    url = tracking_url(lead_id, sequence_id)
    return (
        f'<img src="{url}" width="1" height="1" '
        f'alt="" style="display:none;border:0;width:1px;height:1px" />'
    )


def verify_signature(lead_id: int, sequence_id: int, signature: str) -> bool:
    """Constant-time signature comparison for the tracking server."""
    if not signature:
        return False
    expected = _sign(lead_id, sequence_id)
    return hmac.compare_digest(expected, signature)
